# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dc_debug.ui'
#
# Created: Tue Jun 17 13:50:09 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1232, 864)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label_69 = QtGui.QLabel(self.centralwidget)
        self.label_69.setGeometry(QtCore.QRect(700, 220, 91, 16))
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.label_76 = QtGui.QLabel(self.centralwidget)
        self.label_76.setGeometry(QtCore.QRect(700, 730, 53, 15))
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.osa_smsr = QtGui.QLabel(self.centralwidget)
        self.osa_smsr.setGeometry(QtCore.QRect(770, 730, 51, 16))
        self.osa_smsr.setMinimumSize(QtCore.QSize(51, 0))
        self.osa_smsr.setObjectName(_fromUtf8("osa_smsr"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(700, 350, 521, 371))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.osa_trace_layout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.osa_trace_layout.setMargin(0)
        self.osa_trace_layout.setObjectName(_fromUtf8("osa_trace_layout"))
        self.osa_sweep = QtGui.QPushButton(self.centralwidget)
        self.osa_sweep.setGeometry(QtCore.QRect(1130, 760, 91, 24))
        self.osa_sweep.setObjectName(_fromUtf8("osa_sweep"))
        self.save_settings_button = QtGui.QPushButton(self.centralwidget)
        self.save_settings_button.setEnabled(False)
        self.save_settings_button.setGeometry(QtCore.QRect(1130, 790, 91, 24))
        self.save_settings_button.setObjectName(_fromUtf8("save_settings_button"))
        self.load_settings_button = QtGui.QPushButton(self.centralwidget)
        self.load_settings_button.setEnabled(False)
        self.load_settings_button.setGeometry(QtCore.QRect(1040, 790, 91, 24))
        self.load_settings_button.setObjectName(_fromUtf8("load_settings_button"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(661, 10, 531, 26))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.gpib_connection = QtGui.QComboBox(self.layoutWidget)
        self.gpib_connection.setObjectName(_fromUtf8("gpib_connection"))
        self.gpib_connection.addItem(_fromUtf8(""))
        self.gpib_connection.addItem(_fromUtf8(""))
        self.gpib_connection.addItem(_fromUtf8(""))
        self.gpib_connection.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.gpib_connection)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.gpib_connection_text = QtGui.QLineEdit(self.layoutWidget)
        self.gpib_connection_text.setObjectName(_fromUtf8("gpib_connection_text"))
        self.horizontalLayout.addWidget(self.gpib_connection_text)
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout.addWidget(self.label_8)
        self.gpib_connection_bus = QtGui.QLineEdit(self.layoutWidget)
        self.gpib_connection_bus.setMaximumSize(QtCore.QSize(40, 16777215))
        self.gpib_connection_bus.setObjectName(_fromUtf8("gpib_connection_bus"))
        self.horizontalLayout.addWidget(self.gpib_connection_bus)
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 259, 26))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.layoutWidget1)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.laser_sections = QtGui.QComboBox(self.layoutWidget1)
        self.laser_sections.setObjectName(_fromUtf8("laser_sections"))
        self.laser_sections.addItem(_fromUtf8(""))
        self.laser_sections.addItem(_fromUtf8(""))
        self.laser_sections.addItem(_fromUtf8(""))
        self.laser_sections.addItem(_fromUtf8(""))
        self.laser_sections.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.laser_sections)
        self.layoutWidget2 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(700, 110, 221, 26))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_17.setMargin(0)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_58 = QtGui.QLabel(self.layoutWidget2)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.horizontalLayout_17.addWidget(self.label_58)
        self.is_value = QtGui.QLabel(self.layoutWidget2)
        self.is_value.setObjectName(_fromUtf8("is_value"))
        self.horizontalLayout_17.addWidget(self.is_value)
        self.label_10 = QtGui.QLabel(self.layoutWidget2)
        self.label_10.setMaximumSize(QtCore.QSize(22, 16777215))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_17.addWidget(self.label_10)
        self.is_get_value = QtGui.QPushButton(self.layoutWidget2)
        self.is_get_value.setObjectName(_fromUtf8("is_get_value"))
        self.horizontalLayout_17.addWidget(self.is_get_value)
        self.layoutWidget3 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(700, 150, 508, 38))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_18.setMargin(0)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_60 = QtGui.QLabel(self.layoutWidget3)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.horizontalLayout_18.addWidget(self.label_60)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_61 = QtGui.QLabel(self.layoutWidget3)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.verticalLayout.addWidget(self.label_61)
        self.label_62 = QtGui.QLabel(self.layoutWidget3)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.verticalLayout.addWidget(self.label_62)
        self.horizontalLayout_18.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.wm_peak1_wavelength = QtGui.QLabel(self.layoutWidget3)
        self.wm_peak1_wavelength.setMinimumSize(QtCore.QSize(59, 0))
        self.wm_peak1_wavelength.setObjectName(_fromUtf8("wm_peak1_wavelength"))
        self.verticalLayout_2.addWidget(self.wm_peak1_wavelength)
        self.wm_peak2_wavelength = QtGui.QLabel(self.layoutWidget3)
        self.wm_peak2_wavelength.setMinimumSize(QtCore.QSize(59, 0))
        self.wm_peak2_wavelength.setObjectName(_fromUtf8("wm_peak2_wavelength"))
        self.verticalLayout_2.addWidget(self.wm_peak2_wavelength)
        self.horizontalLayout_18.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_65 = QtGui.QLabel(self.layoutWidget3)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.verticalLayout_3.addWidget(self.label_65)
        self.label_66 = QtGui.QLabel(self.layoutWidget3)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.verticalLayout_3.addWidget(self.label_66)
        self.horizontalLayout_18.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.wm_peak1_power = QtGui.QLabel(self.layoutWidget3)
        self.wm_peak1_power.setMinimumSize(QtCore.QSize(49, 0))
        self.wm_peak1_power.setObjectName(_fromUtf8("wm_peak1_power"))
        self.verticalLayout_4.addWidget(self.wm_peak1_power)
        self.wm_peak2_power = QtGui.QLabel(self.layoutWidget3)
        self.wm_peak2_power.setMinimumSize(QtCore.QSize(49, 0))
        self.wm_peak2_power.setObjectName(_fromUtf8("wm_peak2_power"))
        self.verticalLayout_4.addWidget(self.wm_peak2_power)
        self.horizontalLayout_18.addLayout(self.verticalLayout_4)
        self.wm_get_values = QtGui.QPushButton(self.layoutWidget3)
        self.wm_get_values.setObjectName(_fromUtf8("wm_get_values"))
        self.horizontalLayout_18.addWidget(self.wm_get_values)
        self.layoutWidget4 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(450, 50, 181, 26))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(self.layoutWidget4)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.is_connect = QtGui.QPushButton(self.layoutWidget4)
        self.is_connect.setObjectName(_fromUtf8("is_connect"))
        self.horizontalLayout_4.addWidget(self.is_connect)
        self.layoutWidget5 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget5.setGeometry(QtCore.QRect(630, 50, 291, 26))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_6 = QtGui.QLabel(self.layoutWidget5)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_5.addWidget(self.label_6)
        self.wavemeter_gpib = QtGui.QLineEdit(self.layoutWidget5)
        self.wavemeter_gpib.setObjectName(_fromUtf8("wavemeter_gpib"))
        self.horizontalLayout_5.addWidget(self.wavemeter_gpib)
        self.wavemeter_connect = QtGui.QPushButton(self.layoutWidget5)
        self.wavemeter_connect.setObjectName(_fromUtf8("wavemeter_connect"))
        self.horizontalLayout_5.addWidget(self.wavemeter_connect)
        self.layoutWidget6 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget6.setGeometry(QtCore.QRect(930, 50, 289, 26))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_7 = QtGui.QLabel(self.layoutWidget6)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_6.addWidget(self.label_7)
        self.osa_ip = QtGui.QLineEdit(self.layoutWidget6)
        self.osa_ip.setObjectName(_fromUtf8("osa_ip"))
        self.horizontalLayout_6.addWidget(self.osa_ip)
        self.osa_connect = QtGui.QPushButton(self.layoutWidget6)
        self.osa_connect.setObjectName(_fromUtf8("osa_connect"))
        self.horizontalLayout_6.addWidget(self.osa_connect)
        self.layoutWidget7 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget7.setGeometry(QtCore.QRect(810, 220, 179, 26))
        self.layoutWidget7.setObjectName(_fromUtf8("layoutWidget7"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_19.setMargin(0)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_70 = QtGui.QLabel(self.layoutWidget7)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.horizontalLayout_19.addWidget(self.label_70)
        self.osa_vbw = QtGui.QComboBox(self.layoutWidget7)
        self.osa_vbw.setObjectName(_fromUtf8("osa_vbw"))
        self.osa_vbw.addItem(_fromUtf8(""))
        self.osa_vbw.addItem(_fromUtf8(""))
        self.osa_vbw.addItem(_fromUtf8(""))
        self.osa_vbw.addItem(_fromUtf8(""))
        self.osa_vbw.addItem(_fromUtf8(""))
        self.osa_vbw.addItem(_fromUtf8(""))
        self.osa_vbw.addItem(_fromUtf8(""))
        self.osa_vbw.addItem(_fromUtf8(""))
        self.horizontalLayout_19.addWidget(self.osa_vbw)
        self.layoutWidget8 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget8.setGeometry(QtCore.QRect(810, 250, 290, 26))
        self.layoutWidget8.setObjectName(_fromUtf8("layoutWidget8"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.layoutWidget8)
        self.horizontalLayout_20.setMargin(0)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_72 = QtGui.QLabel(self.layoutWidget8)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.horizontalLayout_20.addWidget(self.label_72)
        self.osa_resolution = QtGui.QComboBox(self.layoutWidget8)
        self.osa_resolution.setObjectName(_fromUtf8("osa_resolution"))
        self.osa_resolution.addItem(_fromUtf8(""))
        self.osa_resolution.addItem(_fromUtf8(""))
        self.osa_resolution.addItem(_fromUtf8(""))
        self.osa_resolution.addItem(_fromUtf8(""))
        self.osa_resolution.addItem(_fromUtf8(""))
        self.osa_resolution.addItem(_fromUtf8(""))
        self.osa_resolution.addItem(_fromUtf8(""))
        self.horizontalLayout_20.addWidget(self.osa_resolution)
        self.label_71 = QtGui.QLabel(self.layoutWidget8)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.horizontalLayout_20.addWidget(self.label_71)
        self.osa_sampling = QtGui.QComboBox(self.layoutWidget8)
        self.osa_sampling.setObjectName(_fromUtf8("osa_sampling"))
        self.osa_sampling.addItem(_fromUtf8(""))
        self.osa_sampling.addItem(_fromUtf8(""))
        self.osa_sampling.addItem(_fromUtf8(""))
        self.osa_sampling.addItem(_fromUtf8(""))
        self.osa_sampling.addItem(_fromUtf8(""))
        self.osa_sampling.addItem(_fromUtf8(""))
        self.osa_sampling.addItem(_fromUtf8(""))
        self.osa_sampling.addItem(_fromUtf8(""))
        self.osa_sampling.addItem(_fromUtf8(""))
        self.osa_sampling.addItem(_fromUtf8(""))
        self.horizontalLayout_20.addWidget(self.osa_sampling)
        self.layoutWidget9 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget9.setGeometry(QtCore.QRect(700, 280, 521, 26))
        self.layoutWidget9.setObjectName(_fromUtf8("layoutWidget9"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.layoutWidget9)
        self.horizontalLayout_21.setMargin(0)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_73 = QtGui.QLabel(self.layoutWidget9)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.horizontalLayout_21.addWidget(self.label_73)
        self.osa_start = QtGui.QLineEdit(self.layoutWidget9)
        self.osa_start.setObjectName(_fromUtf8("osa_start"))
        self.horizontalLayout_21.addWidget(self.osa_start)
        self.label_74 = QtGui.QLabel(self.layoutWidget9)
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.horizontalLayout_21.addWidget(self.label_74)
        self.osa_stop = QtGui.QLineEdit(self.layoutWidget9)
        self.osa_stop.setObjectName(_fromUtf8("osa_stop"))
        self.horizontalLayout_21.addWidget(self.osa_stop)
        self.osa_start_stop_save = QtGui.QPushButton(self.layoutWidget9)
        self.osa_start_stop_save.setObjectName(_fromUtf8("osa_start_stop_save"))
        self.horizontalLayout_21.addWidget(self.osa_start_stop_save)
        self.layoutWidget10 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget10.setGeometry(QtCore.QRect(700, 310, 451, 26))
        self.layoutWidget10.setObjectName(_fromUtf8("layoutWidget10"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout(self.layoutWidget10)
        self.horizontalLayout_22.setMargin(0)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_75 = QtGui.QLabel(self.layoutWidget10)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.horizontalLayout_22.addWidget(self.label_75)
        self.osa_center = QtGui.QLineEdit(self.layoutWidget10)
        self.osa_center.setObjectName(_fromUtf8("osa_center"))
        self.horizontalLayout_22.addWidget(self.osa_center)
        self.label_3 = QtGui.QLabel(self.layoutWidget10)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_22.addWidget(self.label_3)
        self.osa_span = QtGui.QLineEdit(self.layoutWidget10)
        self.osa_span.setObjectName(_fromUtf8("osa_span"))
        self.horizontalLayout_22.addWidget(self.osa_span)
        self.osa_center_span_save = QtGui.QPushButton(self.layoutWidget10)
        self.osa_center_span_save.setObjectName(_fromUtf8("osa_center_span_save"))
        self.horizontalLayout_22.addWidget(self.osa_center_span_save)
        self.laser_sections_connect = QtGui.QPushButton(self.centralwidget)
        self.laser_sections_connect.setGeometry(QtCore.QRect(270, 10, 91, 24))
        self.laser_sections_connect.setObjectName(_fromUtf8("laser_sections_connect"))
        self.refresh_check = QtGui.QCheckBox(self.centralwidget)
        self.refresh_check.setGeometry(QtCore.QRect(20, 50, 151, 21))
        self.refresh_check.setObjectName(_fromUtf8("refresh_check"))
        self.refresh_seconds = QtGui.QLineEdit(self.centralwidget)
        self.refresh_seconds.setGeometry(QtCore.QRect(160, 50, 51, 23))
        self.refresh_seconds.setObjectName(_fromUtf8("refresh_seconds"))
        self.zero_laser = QtGui.QPushButton(self.centralwidget)
        self.zero_laser.setGeometry(QtCore.QRect(20, 800, 91, 24))
        self.zero_laser.setObjectName(_fromUtf8("zero_laser"))
        self.osa_progress = QtGui.QProgressBar(self.centralwidget)
        self.osa_progress.setGeometry(QtCore.QRect(1100, 730, 118, 23))
        self.osa_progress.setProperty("value", 0)
        self.osa_progress.setObjectName(_fromUtf8("osa_progress"))
        self.layoutWidget_10 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_10.setGeometry(QtCore.QRect(700, 750, 381, 38))
        self.layoutWidget_10.setObjectName(_fromUtf8("layoutWidget_10"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout(self.layoutWidget_10)
        self.horizontalLayout_24.setMargin(0)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_64 = QtGui.QLabel(self.layoutWidget_10)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.verticalLayout_5.addWidget(self.label_64)
        self.label_67 = QtGui.QLabel(self.layoutWidget_10)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.verticalLayout_5.addWidget(self.label_67)
        self.horizontalLayout_24.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.osa_peak1_wavelength = QtGui.QLabel(self.layoutWidget_10)
        self.osa_peak1_wavelength.setMinimumSize(QtCore.QSize(59, 0))
        self.osa_peak1_wavelength.setObjectName(_fromUtf8("osa_peak1_wavelength"))
        self.verticalLayout_6.addWidget(self.osa_peak1_wavelength)
        self.osa_peak2_wavelength = QtGui.QLabel(self.layoutWidget_10)
        self.osa_peak2_wavelength.setMinimumSize(QtCore.QSize(59, 0))
        self.osa_peak2_wavelength.setObjectName(_fromUtf8("osa_peak2_wavelength"))
        self.verticalLayout_6.addWidget(self.osa_peak2_wavelength)
        self.horizontalLayout_24.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_68 = QtGui.QLabel(self.layoutWidget_10)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.verticalLayout_7.addWidget(self.label_68)
        self.label_77 = QtGui.QLabel(self.layoutWidget_10)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.verticalLayout_7.addWidget(self.label_77)
        self.horizontalLayout_24.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.osa_peak1_power = QtGui.QLabel(self.layoutWidget_10)
        self.osa_peak1_power.setMinimumSize(QtCore.QSize(49, 0))
        self.osa_peak1_power.setObjectName(_fromUtf8("osa_peak1_power"))
        self.verticalLayout_8.addWidget(self.osa_peak1_power)
        self.osa_peak2_power = QtGui.QLabel(self.layoutWidget_10)
        self.osa_peak2_power.setMinimumSize(QtCore.QSize(49, 0))
        self.osa_peak2_power.setObjectName(_fromUtf8("osa_peak2_power"))
        self.verticalLayout_8.addWidget(self.osa_peak2_power)
        self.horizontalLayout_24.addLayout(self.verticalLayout_8)
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(20, 80, 671, 721))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setEnabled(True)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 648, 715))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.electrode_layout = QtGui.QVBoxLayout()
        self.electrode_layout.setObjectName(_fromUtf8("electrode_layout"))
        self.verticalLayout_10.addLayout(self.electrode_layout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1232, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "DC Debug", None))
        self.label_69.setText(_translate("MainWindow", "OSA Parameters:", None))
        self.label_76.setText(_translate("MainWindow", "SMSR", None))
        self.osa_smsr.setText(_translate("MainWindow", "---", None))
        self.osa_sweep.setText(_translate("MainWindow", "Sweep OSA", None))
        self.save_settings_button.setText(_translate("MainWindow", "Save Settings", None))
        self.load_settings_button.setText(_translate("MainWindow", "Load Settings", None))
        self.label_4.setText(_translate("MainWindow", "GPIB Connection", None))
        self.gpib_connection.setItemText(0, _translate("MainWindow", "NI VISA", None))
        self.gpib_connection.setItemText(1, _translate("MainWindow", "Prologix Ethernet", None))
        self.gpib_connection.setItemText(2, _translate("MainWindow", "Prologix USB", None))
        self.gpib_connection.setItemText(3, _translate("MainWindow", "Dummy", None))
        self.label_5.setText(_translate("MainWindow", "GPIB IP/Serial Port", None))
        self.label_8.setText(_translate("MainWindow", "GPIB Bus", None))
        self.gpib_connection_bus.setText(_translate("MainWindow", "0", None))
        self.label.setText(_translate("MainWindow", "Laser Connection", None))
        self.laser_sections.setItemText(0, _translate("MainWindow", "DC Test Station", None))
        self.laser_sections.setItemText(1, _translate("MainWindow", "RF Test Station (TOSA)", None))
        self.laser_sections.setItemText(2, _translate("MainWindow", "RF Test Station (COC)", None))
        self.laser_sections.setItemText(3, _translate("MainWindow", "SFP DACs", None))
        self.laser_sections.setItemText(4, _translate("MainWindow", "Dummy", None))
        self.label_58.setText(_translate("MainWindow", "IS Value:", None))
        self.is_value.setText(_translate("MainWindow", "---", None))
        self.label_10.setText(_translate("MainWindow", "mW", None))
        self.is_get_value.setText(_translate("MainWindow", "Get Value", None))
        self.label_60.setText(_translate("MainWindow", "Wavemeter Values:", None))
        self.label_61.setText(_translate("MainWindow", "Peak 1 Wavelength", None))
        self.label_62.setText(_translate("MainWindow", "Peak 2 Wavelength", None))
        self.wm_peak1_wavelength.setText(_translate("MainWindow", "---", None))
        self.wm_peak2_wavelength.setText(_translate("MainWindow", "---", None))
        self.label_65.setText(_translate("MainWindow", "Peak 1 Power", None))
        self.label_66.setText(_translate("MainWindow", "Peak 2 Power", None))
        self.wm_peak1_power.setText(_translate("MainWindow", "---", None))
        self.wm_peak2_power.setText(_translate("MainWindow", "---", None))
        self.wm_get_values.setText(_translate("MainWindow", "Get Values", None))
        self.label_2.setText(_translate("MainWindow", "Integrating Sphere", None))
        self.is_connect.setText(_translate("MainWindow", "Connect", None))
        self.label_6.setText(_translate("MainWindow", "Wavemeter (HP86120B) GPIB", None))
        self.wavemeter_connect.setText(_translate("MainWindow", "Connect", None))
        self.label_7.setText(_translate("MainWindow", "OSA (MS9740) IP:", None))
        self.osa_connect.setText(_translate("MainWindow", "Connect", None))
        self.label_70.setText(_translate("MainWindow", "Video Bandwidth", None))
        self.osa_vbw.setItemText(0, _translate("MainWindow", "10 Hz", None))
        self.osa_vbw.setItemText(1, _translate("MainWindow", "100 Hz", None))
        self.osa_vbw.setItemText(2, _translate("MainWindow", "200 Hz", None))
        self.osa_vbw.setItemText(3, _translate("MainWindow", "1 kHz", None))
        self.osa_vbw.setItemText(4, _translate("MainWindow", "2 kHz", None))
        self.osa_vbw.setItemText(5, _translate("MainWindow", "10 kHz", None))
        self.osa_vbw.setItemText(6, _translate("MainWindow", "100 kHz", None))
        self.osa_vbw.setItemText(7, _translate("MainWindow", "1 MHz", None))
        self.label_72.setText(_translate("MainWindow", "Resolution", None))
        self.osa_resolution.setItemText(0, _translate("MainWindow", "0.03", None))
        self.osa_resolution.setItemText(1, _translate("MainWindow", "0.05", None))
        self.osa_resolution.setItemText(2, _translate("MainWindow", "0.07", None))
        self.osa_resolution.setItemText(3, _translate("MainWindow", "0.1", None))
        self.osa_resolution.setItemText(4, _translate("MainWindow", "0.2", None))
        self.osa_resolution.setItemText(5, _translate("MainWindow", "0.5", None))
        self.osa_resolution.setItemText(6, _translate("MainWindow", "1.0", None))
        self.label_71.setText(_translate("MainWindow", "Sampling Points", None))
        self.osa_sampling.setItemText(0, _translate("MainWindow", "51", None))
        self.osa_sampling.setItemText(1, _translate("MainWindow", "101", None))
        self.osa_sampling.setItemText(2, _translate("MainWindow", "251", None))
        self.osa_sampling.setItemText(3, _translate("MainWindow", "501", None))
        self.osa_sampling.setItemText(4, _translate("MainWindow", "1001", None))
        self.osa_sampling.setItemText(5, _translate("MainWindow", "2001", None))
        self.osa_sampling.setItemText(6, _translate("MainWindow", "5001", None))
        self.osa_sampling.setItemText(7, _translate("MainWindow", "10001", None))
        self.osa_sampling.setItemText(8, _translate("MainWindow", "20001", None))
        self.osa_sampling.setItemText(9, _translate("MainWindow", "50001", None))
        self.label_73.setText(_translate("MainWindow", "Start Wavelength (nm)", None))
        self.label_74.setText(_translate("MainWindow", "Stop Wavelength (nm)", None))
        self.osa_start_stop_save.setText(_translate("MainWindow", "Save Values", None))
        self.label_75.setText(_translate("MainWindow", "Center Wavelength (nm)", None))
        self.label_3.setText(_translate("MainWindow", "Span (nm)", None))
        self.osa_center_span_save.setText(_translate("MainWindow", "Save Values", None))
        self.laser_sections_connect.setText(_translate("MainWindow", "Connect", None))
        self.refresh_check.setText(_translate("MainWindow", "Output Refresh (sec)", None))
        self.refresh_seconds.setText(_translate("MainWindow", "0.5", None))
        self.zero_laser.setText(_translate("MainWindow", "Zero Laser", None))
        self.label_64.setText(_translate("MainWindow", "Peak 1 Wavelength", None))
        self.label_67.setText(_translate("MainWindow", "Peak 2 Wavelength", None))
        self.osa_peak1_wavelength.setText(_translate("MainWindow", "---", None))
        self.osa_peak2_wavelength.setText(_translate("MainWindow", "---", None))
        self.label_68.setText(_translate("MainWindow", "Peak 1 Power", None))
        self.label_77.setText(_translate("MainWindow", "Peak 2 Power", None))
        self.osa_peak1_power.setText(_translate("MainWindow", "---", None))
        self.osa_peak2_power.setText(_translate("MainWindow", "---", None))

