# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_current_maximums.ui'
#
# Created: Thu Mar 13 21:34:25 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(426, 274)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(340, 240, 81, 31))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 40, 81, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 81, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 60, 81, 31))
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 130, 81, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 160, 81, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(30, 220, 81, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(30, 190, 81, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.mirror1_maximum = QtGui.QLineEdit(Dialog)
        self.mirror1_maximum.setGeometry(QtCore.QRect(120, 30, 81, 23))
        self.mirror1_maximum.setText(_fromUtf8(""))
        self.mirror1_maximum.setObjectName(_fromUtf8("mirror1_maximum"))
        self.gain_maximum = QtGui.QLineEdit(Dialog)
        self.gain_maximum.setGeometry(QtCore.QRect(120, 90, 81, 23))
        self.gain_maximum.setText(_fromUtf8(""))
        self.gain_maximum.setObjectName(_fromUtf8("gain_maximum"))
        self.phase1_maximum = QtGui.QLineEdit(Dialog)
        self.phase1_maximum.setGeometry(QtCore.QRect(120, 210, 81, 23))
        self.phase1_maximum.setText(_fromUtf8(""))
        self.phase1_maximum.setObjectName(_fromUtf8("phase1_maximum"))
        self.mirror2_maximum = QtGui.QLineEdit(Dialog)
        self.mirror2_maximum.setGeometry(QtCore.QRect(120, 120, 81, 23))
        self.mirror2_maximum.setText(_fromUtf8(""))
        self.mirror2_maximum.setObjectName(_fromUtf8("mirror2_maximum"))
        self.soa1_maximum = QtGui.QLineEdit(Dialog)
        self.soa1_maximum.setGeometry(QtCore.QRect(120, 150, 81, 23))
        self.soa1_maximum.setText(_fromUtf8(""))
        self.soa1_maximum.setObjectName(_fromUtf8("soa1_maximum"))
        self.soa2_maximum = QtGui.QLineEdit(Dialog)
        self.soa2_maximum.setGeometry(QtCore.QRect(120, 180, 81, 23))
        self.soa2_maximum.setText(_fromUtf8(""))
        self.soa2_maximum.setObjectName(_fromUtf8("soa2_maximum"))
        self.laser_phase_maximum = QtGui.QLineEdit(Dialog)
        self.laser_phase_maximum.setGeometry(QtCore.QRect(120, 60, 81, 23))
        self.laser_phase_maximum.setText(_fromUtf8(""))
        self.laser_phase_maximum.setObjectName(_fromUtf8("laser_phase_maximum"))
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(110, 10, 101, 20))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(220, 10, 81, 21))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.mirror1_dithering = QtGui.QLineEdit(Dialog)
        self.mirror1_dithering.setGeometry(QtCore.QRect(220, 30, 81, 23))
        self.mirror1_dithering.setText(_fromUtf8(""))
        self.mirror1_dithering.setObjectName(_fromUtf8("mirror1_dithering"))
        self.laser_phase_dithering = QtGui.QLineEdit(Dialog)
        self.laser_phase_dithering.setGeometry(QtCore.QRect(220, 60, 81, 23))
        self.laser_phase_dithering.setText(_fromUtf8(""))
        self.laser_phase_dithering.setObjectName(_fromUtf8("laser_phase_dithering"))
        self.mirror2_dithering = QtGui.QLineEdit(Dialog)
        self.mirror2_dithering.setGeometry(QtCore.QRect(220, 120, 81, 23))
        self.mirror2_dithering.setText(_fromUtf8(""))
        self.mirror2_dithering.setObjectName(_fromUtf8("mirror2_dithering"))
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(320, 10, 101, 21))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.mirror1_time_constant = QtGui.QLineEdit(Dialog)
        self.mirror1_time_constant.setGeometry(QtCore.QRect(330, 30, 81, 23))
        self.mirror1_time_constant.setText(_fromUtf8(""))
        self.mirror1_time_constant.setObjectName(_fromUtf8("mirror1_time_constant"))
        self.laser_phase_time_constant = QtGui.QLineEdit(Dialog)
        self.laser_phase_time_constant.setGeometry(QtCore.QRect(330, 60, 81, 23))
        self.laser_phase_time_constant.setText(_fromUtf8(""))
        self.laser_phase_time_constant.setObjectName(_fromUtf8("laser_phase_time_constant"))
        self.label_11 = QtGui.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(320, 140, 101, 41))
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.default_button = QtGui.QPushButton(Dialog)
        self.default_button.setGeometry(QtCore.QRect(330, 180, 91, 24))
        self.default_button.setObjectName(_fromUtf8("default_button"))
        self.load_button = QtGui.QPushButton(Dialog)
        self.load_button.setGeometry(QtCore.QRect(230, 210, 91, 24))
        self.load_button.setObjectName(_fromUtf8("load_button"))
        self.save_button = QtGui.QPushButton(Dialog)
        self.save_button.setGeometry(QtCore.QRect(330, 210, 91, 24))
        self.save_button.setObjectName(_fromUtf8("save_button"))
        self.label_12 = QtGui.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(30, 250, 81, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.phase2_maximum = QtGui.QLineEdit(Dialog)
        self.phase2_maximum.setGeometry(QtCore.QRect(120, 240, 81, 23))
        self.phase2_maximum.setText(_fromUtf8(""))
        self.phase2_maximum.setObjectName(_fromUtf8("phase2_maximum"))

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Current Maximums", None))
        self.label.setText(_translate("Dialog", "Mirror 1", None))
        self.label_2.setText(_translate("Dialog", "Gain", None))
        self.label_3.setText(_translate("Dialog", "Laser Phase", None))
        self.label_4.setText(_translate("Dialog", "Mirror 2", None))
        self.label_5.setText(_translate("Dialog", "SOA 1 Section", None))
        self.label_6.setText(_translate("Dialog", "Phase 1", None))
        self.label_7.setText(_translate("Dialog", "SOA 2 Section", None))
        self.label_8.setText(_translate("Dialog", "Max Current (mA)", None))
        self.label_9.setText(_translate("Dialog", "Dithering (mA)", None))
        self.label_10.setText(_translate("Dialog", "Time Constant (µs)", None))
        self.label_11.setText(_translate("Dialog", "Time Constant Same As Mirror 1", None))
        self.default_button.setText(_translate("Dialog", "Load Defaults", None))
        self.load_button.setText(_translate("Dialog", "Load Settings", None))
        self.save_button.setText(_translate("Dialog", "Save Settings", None))
        self.label_12.setText(_translate("Dialog", "Phase 2", None))

