# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_etalon_alignment.ui'
#
# Created: Thu Dec  5 12:32:54 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(811, 411)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(430, 360, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 80, 281, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 150, 331, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 290, 331, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 220, 331, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.reference_power_in_adc = QtGui.QLabel(Dialog)
        self.reference_power_in_adc.setGeometry(QtCore.QRect(420, 80, 131, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.reference_power_in_adc.setFont(font)
        self.reference_power_in_adc.setObjectName(_fromUtf8("reference_power_in_adc"))
        self.laser_temp_adc = QtGui.QLabel(Dialog)
        self.laser_temp_adc.setGeometry(QtCore.QRect(420, 290, 131, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.laser_temp_adc.setFont(font)
        self.laser_temp_adc.setObjectName(_fromUtf8("laser_temp_adc"))
        self.output_power_adc = QtGui.QLabel(Dialog)
        self.output_power_adc.setGeometry(QtCore.QRect(420, 220, 131, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.output_power_adc.setFont(font)
        self.output_power_adc.setObjectName(_fromUtf8("output_power_adc"))
        self.etalon_power_in_adc = QtGui.QLabel(Dialog)
        self.etalon_power_in_adc.setGeometry(QtCore.QRect(420, 150, 131, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.etalon_power_in_adc.setFont(font)
        self.etalon_power_in_adc.setObjectName(_fromUtf8("etalon_power_in_adc"))
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(430, 20, 131, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.reference_power_in = QtGui.QLabel(Dialog)
        self.reference_power_in.setGeometry(QtCore.QRect(600, 80, 191, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.reference_power_in.setFont(font)
        self.reference_power_in.setObjectName(_fromUtf8("reference_power_in"))
        self.reference_power_in_3 = QtGui.QLabel(Dialog)
        self.reference_power_in_3.setGeometry(QtCore.QRect(600, 20, 191, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.reference_power_in_3.setFont(font)
        self.reference_power_in_3.setObjectName(_fromUtf8("reference_power_in_3"))
        self.etalon_power_in = QtGui.QLabel(Dialog)
        self.etalon_power_in.setGeometry(QtCore.QRect(600, 140, 191, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.etalon_power_in.setFont(font)
        self.etalon_power_in.setObjectName(_fromUtf8("etalon_power_in"))
        self.output_power = QtGui.QLabel(Dialog)
        self.output_power.setGeometry(QtCore.QRect(600, 210, 191, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.output_power.setFont(font)
        self.output_power.setObjectName(_fromUtf8("output_power"))
        self.laser_temp = QtGui.QLabel(Dialog)
        self.laser_temp.setGeometry(QtCore.QRect(600, 280, 191, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.laser_temp.setFont(font)
        self.laser_temp.setObjectName(_fromUtf8("laser_temp"))

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Etalon Alignment", None))
        self.label.setText(_translate("Dialog", "Ref Power In", None))
        self.label_2.setText(_translate("Dialog", "Etalon Power In", None))
        self.label_3.setText(_translate("Dialog", "Laser Temp", None))
        self.label_4.setText(_translate("Dialog", "Output Power", None))
        self.reference_power_in_adc.setText(_translate("Dialog", "0", None))
        self.laser_temp_adc.setText(_translate("Dialog", "0", None))
        self.output_power_adc.setText(_translate("Dialog", "0", None))
        self.etalon_power_in_adc.setText(_translate("Dialog", "0", None))
        self.label_5.setText(_translate("Dialog", "ADC", None))
        self.reference_power_in.setText(_translate("Dialog", "0.000", None))
        self.reference_power_in_3.setText(_translate("Dialog", "V / °C", None))
        self.etalon_power_in.setText(_translate("Dialog", "0.000", None))
        self.output_power.setText(_translate("Dialog", "0.000", None))
        self.laser_temp.setText(_translate("Dialog", "0.000", None))

