# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_iv_curves.ui'
#
# Created: Thu Jun 12 15:29:28 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1060, 846)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.laser_sections_combo = QtGui.QComboBox(self.centralwidget)
        self.laser_sections_combo.setGeometry(QtCore.QRect(120, 10, 111, 24))
        self.laser_sections_combo.setObjectName(_fromUtf8("laser_sections_combo"))
        self.laser_sections_combo.addItem(_fromUtf8(""))
        self.laser_sections_combo.addItem(_fromUtf8(""))
        self.laser_sections_combo.addItem(_fromUtf8(""))
        self.laser_sections_combo.addItem(_fromUtf8(""))
        self.laser_sections_combo.addItem(_fromUtf8(""))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 101, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(260, 10, 31, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.uid_text = QtGui.QLineEdit(self.centralwidget)
        self.uid_text.setGeometry(QtCore.QRect(300, 10, 113, 23))
        self.uid_text.setObjectName(_fromUtf8("uid_text"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(420, 10, 41, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.laser_stage_combo = QtGui.QComboBox(self.centralwidget)
        self.laser_stage_combo.setGeometry(QtCore.QRect(470, 10, 78, 24))
        self.laser_stage_combo.setObjectName(_fromUtf8("laser_stage_combo"))
        self.laser_stage_combo.addItem(_fromUtf8(""))
        self.laser_stage_combo.addItem(_fromUtf8(""))
        self.laser_stage_combo.addItem(_fromUtf8(""))
        self.laser_stage_combo.addItem(_fromUtf8(""))
        self.laser_stage_combo.addItem(_fromUtf8(""))
        self.laser_stage_combo.addItem(_fromUtf8(""))
        self.laser_stage_combo.addItem(_fromUtf8(""))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 40, 81, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.filepath_base = QtGui.QLineEdit(self.centralwidget)
        self.filepath_base.setGeometry(QtCore.QRect(120, 40, 431, 23))
        self.filepath_base.setObjectName(_fromUtf8("filepath_base"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 70, 341, 171))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.mirror1_check = QtGui.QCheckBox(self.groupBox)
        self.mirror1_check.setGeometry(QtCore.QRect(10, 20, 79, 21))
        self.mirror1_check.setObjectName(_fromUtf8("mirror1_check"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 70, 53, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(20, 91, 53, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(20, 110, 53, 21))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.mirror1_start_text = QtGui.QLineEdit(self.groupBox)
        self.mirror1_start_text.setGeometry(QtCore.QRect(70, 66, 61, 23))
        self.mirror1_start_text.setObjectName(_fromUtf8("mirror1_start_text"))
        self.mirror1_stop_text = QtGui.QLineEdit(self.groupBox)
        self.mirror1_stop_text.setGeometry(QtCore.QRect(70, 86, 61, 23))
        self.mirror1_stop_text.setObjectName(_fromUtf8("mirror1_stop_text"))
        self.mirror1_step_text = QtGui.QLineEdit(self.groupBox)
        self.mirror1_step_text.setGeometry(QtCore.QRect(70, 106, 61, 23))
        self.mirror1_step_text.setObjectName(_fromUtf8("mirror1_step_text"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(20, 45, 53, 20))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.mirror1_type_combo = QtGui.QComboBox(self.groupBox)
        self.mirror1_type_combo.setEnabled(False)
        self.mirror1_type_combo.setGeometry(QtCore.QRect(70, 40, 71, 24))
        self.mirror1_type_combo.setObjectName(_fromUtf8("mirror1_type_combo"))
        self.mirror1_type_combo.addItem(_fromUtf8(""))
        self.mirror1_type_combo.addItem(_fromUtf8(""))
        self.verticalLayoutWidget = QtGui.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(150, 30, 171, 131))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.mirror1_plot_layout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.mirror1_plot_layout.setMargin(0)
        self.mirror1_plot_layout.setObjectName(_fromUtf8("mirror1_plot_layout"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(360, 70, 341, 171))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.mirror2_check = QtGui.QCheckBox(self.groupBox_2)
        self.mirror2_check.setGeometry(QtCore.QRect(10, 20, 79, 21))
        self.mirror2_check.setObjectName(_fromUtf8("mirror2_check"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(20, 70, 53, 21))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(20, 91, 53, 20))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(20, 110, 53, 21))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.mirror2_start_text = QtGui.QLineEdit(self.groupBox_2)
        self.mirror2_start_text.setGeometry(QtCore.QRect(70, 66, 61, 23))
        self.mirror2_start_text.setObjectName(_fromUtf8("mirror2_start_text"))
        self.mirror2_stop_text = QtGui.QLineEdit(self.groupBox_2)
        self.mirror2_stop_text.setGeometry(QtCore.QRect(70, 86, 61, 23))
        self.mirror2_stop_text.setObjectName(_fromUtf8("mirror2_stop_text"))
        self.mirror2_step_text = QtGui.QLineEdit(self.groupBox_2)
        self.mirror2_step_text.setGeometry(QtCore.QRect(70, 106, 61, 23))
        self.mirror2_step_text.setObjectName(_fromUtf8("mirror2_step_text"))
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(20, 45, 53, 20))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.mirror2_type_combo = QtGui.QComboBox(self.groupBox_2)
        self.mirror2_type_combo.setEnabled(False)
        self.mirror2_type_combo.setGeometry(QtCore.QRect(70, 40, 71, 24))
        self.mirror2_type_combo.setObjectName(_fromUtf8("mirror2_type_combo"))
        self.mirror2_type_combo.addItem(_fromUtf8(""))
        self.mirror2_type_combo.addItem(_fromUtf8(""))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(150, 30, 171, 131))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.mirror2_plot_layout = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.mirror2_plot_layout.setMargin(0)
        self.mirror2_plot_layout.setObjectName(_fromUtf8("mirror2_plot_layout"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(700, 70, 341, 171))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gain_check = QtGui.QCheckBox(self.groupBox_3)
        self.gain_check.setGeometry(QtCore.QRect(10, 20, 79, 21))
        self.gain_check.setObjectName(_fromUtf8("gain_check"))
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(20, 70, 53, 21))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(20, 91, 53, 20))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(20, 110, 53, 21))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gain_start_text = QtGui.QLineEdit(self.groupBox_3)
        self.gain_start_text.setGeometry(QtCore.QRect(70, 66, 61, 23))
        self.gain_start_text.setObjectName(_fromUtf8("gain_start_text"))
        self.gain_stop_text = QtGui.QLineEdit(self.groupBox_3)
        self.gain_stop_text.setGeometry(QtCore.QRect(70, 86, 61, 23))
        self.gain_stop_text.setObjectName(_fromUtf8("gain_stop_text"))
        self.gain_step_text = QtGui.QLineEdit(self.groupBox_3)
        self.gain_step_text.setGeometry(QtCore.QRect(70, 106, 61, 23))
        self.gain_step_text.setObjectName(_fromUtf8("gain_step_text"))
        self.label_16 = QtGui.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(20, 45, 53, 20))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gain_type_combo = QtGui.QComboBox(self.groupBox_3)
        self.gain_type_combo.setEnabled(False)
        self.gain_type_combo.setGeometry(QtCore.QRect(70, 40, 71, 24))
        self.gain_type_combo.setObjectName(_fromUtf8("gain_type_combo"))
        self.gain_type_combo.addItem(_fromUtf8(""))
        self.gain_type_combo.addItem(_fromUtf8(""))
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(150, 30, 171, 131))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.gain_plot_layout = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.gain_plot_layout.setMargin(0)
        self.gain_plot_layout.setObjectName(_fromUtf8("gain_plot_layout"))
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 250, 341, 171))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.soa1_check = QtGui.QCheckBox(self.groupBox_4)
        self.soa1_check.setGeometry(QtCore.QRect(10, 20, 79, 21))
        self.soa1_check.setObjectName(_fromUtf8("soa1_check"))
        self.label_17 = QtGui.QLabel(self.groupBox_4)
        self.label_17.setGeometry(QtCore.QRect(20, 70, 53, 21))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.groupBox_4)
        self.label_18.setGeometry(QtCore.QRect(20, 91, 53, 20))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.groupBox_4)
        self.label_19.setGeometry(QtCore.QRect(20, 110, 53, 21))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.soa1_start_text = QtGui.QLineEdit(self.groupBox_4)
        self.soa1_start_text.setGeometry(QtCore.QRect(70, 66, 61, 23))
        self.soa1_start_text.setObjectName(_fromUtf8("soa1_start_text"))
        self.soa1_stop_text = QtGui.QLineEdit(self.groupBox_4)
        self.soa1_stop_text.setGeometry(QtCore.QRect(70, 86, 61, 23))
        self.soa1_stop_text.setObjectName(_fromUtf8("soa1_stop_text"))
        self.soa1_step_text = QtGui.QLineEdit(self.groupBox_4)
        self.soa1_step_text.setGeometry(QtCore.QRect(70, 106, 61, 23))
        self.soa1_step_text.setObjectName(_fromUtf8("soa1_step_text"))
        self.label_20 = QtGui.QLabel(self.groupBox_4)
        self.label_20.setGeometry(QtCore.QRect(20, 45, 53, 20))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.soa1_type_combo = QtGui.QComboBox(self.groupBox_4)
        self.soa1_type_combo.setEnabled(False)
        self.soa1_type_combo.setGeometry(QtCore.QRect(70, 40, 71, 24))
        self.soa1_type_combo.setObjectName(_fromUtf8("soa1_type_combo"))
        self.soa1_type_combo.addItem(_fromUtf8(""))
        self.soa1_type_combo.addItem(_fromUtf8(""))
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.groupBox_4)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(150, 30, 171, 131))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.soa1_plot_layout = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.soa1_plot_layout.setMargin(0)
        self.soa1_plot_layout.setObjectName(_fromUtf8("soa1_plot_layout"))
        self.groupBox_5 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(360, 250, 341, 171))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.soa2_check = QtGui.QCheckBox(self.groupBox_5)
        self.soa2_check.setGeometry(QtCore.QRect(10, 20, 79, 21))
        self.soa2_check.setObjectName(_fromUtf8("soa2_check"))
        self.label_21 = QtGui.QLabel(self.groupBox_5)
        self.label_21.setGeometry(QtCore.QRect(20, 70, 53, 21))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.groupBox_5)
        self.label_22.setGeometry(QtCore.QRect(20, 91, 53, 20))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(self.groupBox_5)
        self.label_23.setGeometry(QtCore.QRect(20, 110, 53, 21))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.soa2_start_text = QtGui.QLineEdit(self.groupBox_5)
        self.soa2_start_text.setGeometry(QtCore.QRect(70, 66, 61, 23))
        self.soa2_start_text.setObjectName(_fromUtf8("soa2_start_text"))
        self.soa2_stop_text = QtGui.QLineEdit(self.groupBox_5)
        self.soa2_stop_text.setGeometry(QtCore.QRect(70, 86, 61, 23))
        self.soa2_stop_text.setObjectName(_fromUtf8("soa2_stop_text"))
        self.soa2_step_text = QtGui.QLineEdit(self.groupBox_5)
        self.soa2_step_text.setGeometry(QtCore.QRect(70, 106, 61, 23))
        self.soa2_step_text.setObjectName(_fromUtf8("soa2_step_text"))
        self.label_24 = QtGui.QLabel(self.groupBox_5)
        self.label_24.setGeometry(QtCore.QRect(20, 45, 53, 20))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.soa2_type_combo = QtGui.QComboBox(self.groupBox_5)
        self.soa2_type_combo.setEnabled(False)
        self.soa2_type_combo.setGeometry(QtCore.QRect(70, 40, 71, 24))
        self.soa2_type_combo.setObjectName(_fromUtf8("soa2_type_combo"))
        self.soa2_type_combo.addItem(_fromUtf8(""))
        self.soa2_type_combo.addItem(_fromUtf8(""))
        self.verticalLayoutWidget_5 = QtGui.QWidget(self.groupBox_5)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(150, 30, 171, 131))
        self.verticalLayoutWidget_5.setObjectName(_fromUtf8("verticalLayoutWidget_5"))
        self.soa2_plot_layout = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.soa2_plot_layout.setMargin(0)
        self.soa2_plot_layout.setObjectName(_fromUtf8("soa2_plot_layout"))
        self.groupBox_6 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(700, 250, 341, 171))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.laspha_check = QtGui.QCheckBox(self.groupBox_6)
        self.laspha_check.setGeometry(QtCore.QRect(10, 20, 79, 21))
        self.laspha_check.setObjectName(_fromUtf8("laspha_check"))
        self.label_25 = QtGui.QLabel(self.groupBox_6)
        self.label_25.setGeometry(QtCore.QRect(20, 70, 53, 21))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.groupBox_6)
        self.label_26.setGeometry(QtCore.QRect(20, 91, 53, 20))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_27 = QtGui.QLabel(self.groupBox_6)
        self.label_27.setGeometry(QtCore.QRect(20, 110, 53, 21))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.laspha_start_text = QtGui.QLineEdit(self.groupBox_6)
        self.laspha_start_text.setGeometry(QtCore.QRect(70, 66, 61, 23))
        self.laspha_start_text.setObjectName(_fromUtf8("laspha_start_text"))
        self.laspha_stop_text = QtGui.QLineEdit(self.groupBox_6)
        self.laspha_stop_text.setGeometry(QtCore.QRect(70, 86, 61, 23))
        self.laspha_stop_text.setObjectName(_fromUtf8("laspha_stop_text"))
        self.laspha_step_text = QtGui.QLineEdit(self.groupBox_6)
        self.laspha_step_text.setGeometry(QtCore.QRect(70, 106, 61, 23))
        self.laspha_step_text.setObjectName(_fromUtf8("laspha_step_text"))
        self.label_28 = QtGui.QLabel(self.groupBox_6)
        self.label_28.setGeometry(QtCore.QRect(20, 45, 53, 20))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.laspha_type_combo = QtGui.QComboBox(self.groupBox_6)
        self.laspha_type_combo.setEnabled(False)
        self.laspha_type_combo.setGeometry(QtCore.QRect(70, 40, 71, 24))
        self.laspha_type_combo.setObjectName(_fromUtf8("laspha_type_combo"))
        self.laspha_type_combo.addItem(_fromUtf8(""))
        self.laspha_type_combo.addItem(_fromUtf8(""))
        self.verticalLayoutWidget_6 = QtGui.QWidget(self.groupBox_6)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(150, 30, 171, 131))
        self.verticalLayoutWidget_6.setObjectName(_fromUtf8("verticalLayoutWidget_6"))
        self.laspha_plot_layout = QtGui.QVBoxLayout(self.verticalLayoutWidget_6)
        self.laspha_plot_layout.setMargin(0)
        self.laspha_plot_layout.setObjectName(_fromUtf8("laspha_plot_layout"))
        self.groupBox_7 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_7.setGeometry(QtCore.QRect(20, 420, 341, 171))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.phase1_check = QtGui.QCheckBox(self.groupBox_7)
        self.phase1_check.setGeometry(QtCore.QRect(10, 20, 79, 21))
        self.phase1_check.setObjectName(_fromUtf8("phase1_check"))
        self.label_29 = QtGui.QLabel(self.groupBox_7)
        self.label_29.setGeometry(QtCore.QRect(20, 70, 53, 21))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_30 = QtGui.QLabel(self.groupBox_7)
        self.label_30.setGeometry(QtCore.QRect(20, 91, 53, 20))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_31 = QtGui.QLabel(self.groupBox_7)
        self.label_31.setGeometry(QtCore.QRect(20, 110, 53, 21))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.phase1_start_text = QtGui.QLineEdit(self.groupBox_7)
        self.phase1_start_text.setGeometry(QtCore.QRect(70, 66, 61, 23))
        self.phase1_start_text.setObjectName(_fromUtf8("phase1_start_text"))
        self.phase1_stop_text = QtGui.QLineEdit(self.groupBox_7)
        self.phase1_stop_text.setGeometry(QtCore.QRect(70, 86, 61, 23))
        self.phase1_stop_text.setObjectName(_fromUtf8("phase1_stop_text"))
        self.phase1_step_text = QtGui.QLineEdit(self.groupBox_7)
        self.phase1_step_text.setGeometry(QtCore.QRect(70, 106, 61, 23))
        self.phase1_step_text.setObjectName(_fromUtf8("phase1_step_text"))
        self.label_32 = QtGui.QLabel(self.groupBox_7)
        self.label_32.setGeometry(QtCore.QRect(20, 45, 53, 20))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.phase1_type_combo = QtGui.QComboBox(self.groupBox_7)
        self.phase1_type_combo.setEnabled(False)
        self.phase1_type_combo.setGeometry(QtCore.QRect(70, 40, 71, 24))
        self.phase1_type_combo.setObjectName(_fromUtf8("phase1_type_combo"))
        self.phase1_type_combo.addItem(_fromUtf8(""))
        self.phase1_type_combo.addItem(_fromUtf8(""))
        self.verticalLayoutWidget_7 = QtGui.QWidget(self.groupBox_7)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(150, 30, 171, 131))
        self.verticalLayoutWidget_7.setObjectName(_fromUtf8("verticalLayoutWidget_7"))
        self.phase1_plot_layout = QtGui.QVBoxLayout(self.verticalLayoutWidget_7)
        self.phase1_plot_layout.setMargin(0)
        self.phase1_plot_layout.setObjectName(_fromUtf8("phase1_plot_layout"))
        self.groupBox_8 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_8.setGeometry(QtCore.QRect(360, 420, 341, 171))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.mod1_check = QtGui.QCheckBox(self.groupBox_8)
        self.mod1_check.setGeometry(QtCore.QRect(10, 20, 79, 21))
        self.mod1_check.setObjectName(_fromUtf8("mod1_check"))
        self.label_33 = QtGui.QLabel(self.groupBox_8)
        self.label_33.setGeometry(QtCore.QRect(20, 70, 53, 21))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.label_34 = QtGui.QLabel(self.groupBox_8)
        self.label_34.setGeometry(QtCore.QRect(20, 91, 53, 20))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.label_35 = QtGui.QLabel(self.groupBox_8)
        self.label_35.setGeometry(QtCore.QRect(20, 110, 53, 21))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.mod1_start_text = QtGui.QLineEdit(self.groupBox_8)
        self.mod1_start_text.setGeometry(QtCore.QRect(70, 66, 61, 23))
        self.mod1_start_text.setObjectName(_fromUtf8("mod1_start_text"))
        self.mod1_stop_text = QtGui.QLineEdit(self.groupBox_8)
        self.mod1_stop_text.setGeometry(QtCore.QRect(70, 86, 61, 23))
        self.mod1_stop_text.setObjectName(_fromUtf8("mod1_stop_text"))
        self.mod1_step_text = QtGui.QLineEdit(self.groupBox_8)
        self.mod1_step_text.setGeometry(QtCore.QRect(70, 106, 61, 23))
        self.mod1_step_text.setObjectName(_fromUtf8("mod1_step_text"))
        self.label_36 = QtGui.QLabel(self.groupBox_8)
        self.label_36.setGeometry(QtCore.QRect(20, 45, 53, 20))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.mod1_type_combo = QtGui.QComboBox(self.groupBox_8)
        self.mod1_type_combo.setEnabled(False)
        self.mod1_type_combo.setGeometry(QtCore.QRect(70, 40, 71, 24))
        self.mod1_type_combo.setObjectName(_fromUtf8("mod1_type_combo"))
        self.mod1_type_combo.addItem(_fromUtf8(""))
        self.mod1_type_combo.addItem(_fromUtf8(""))
        self.verticalLayoutWidget_8 = QtGui.QWidget(self.groupBox_8)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(150, 30, 171, 131))
        self.verticalLayoutWidget_8.setObjectName(_fromUtf8("verticalLayoutWidget_8"))
        self.mod1_plot_layout = QtGui.QVBoxLayout(self.verticalLayoutWidget_8)
        self.mod1_plot_layout.setMargin(0)
        self.mod1_plot_layout.setObjectName(_fromUtf8("mod1_plot_layout"))
        self.groupBox_9 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_9.setGeometry(QtCore.QRect(700, 420, 341, 171))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.mod2_check = QtGui.QCheckBox(self.groupBox_9)
        self.mod2_check.setGeometry(QtCore.QRect(10, 20, 79, 21))
        self.mod2_check.setObjectName(_fromUtf8("mod2_check"))
        self.label_37 = QtGui.QLabel(self.groupBox_9)
        self.label_37.setGeometry(QtCore.QRect(20, 70, 53, 21))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.label_38 = QtGui.QLabel(self.groupBox_9)
        self.label_38.setGeometry(QtCore.QRect(20, 91, 53, 20))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.label_39 = QtGui.QLabel(self.groupBox_9)
        self.label_39.setGeometry(QtCore.QRect(20, 110, 53, 21))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.mod2_start_text = QtGui.QLineEdit(self.groupBox_9)
        self.mod2_start_text.setGeometry(QtCore.QRect(70, 66, 61, 23))
        self.mod2_start_text.setObjectName(_fromUtf8("mod2_start_text"))
        self.mod2_stop_text = QtGui.QLineEdit(self.groupBox_9)
        self.mod2_stop_text.setGeometry(QtCore.QRect(70, 86, 61, 23))
        self.mod2_stop_text.setObjectName(_fromUtf8("mod2_stop_text"))
        self.mod2_step_text = QtGui.QLineEdit(self.groupBox_9)
        self.mod2_step_text.setGeometry(QtCore.QRect(70, 106, 61, 23))
        self.mod2_step_text.setObjectName(_fromUtf8("mod2_step_text"))
        self.label_40 = QtGui.QLabel(self.groupBox_9)
        self.label_40.setGeometry(QtCore.QRect(20, 45, 53, 20))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.mod2_type_combo = QtGui.QComboBox(self.groupBox_9)
        self.mod2_type_combo.setEnabled(False)
        self.mod2_type_combo.setGeometry(QtCore.QRect(70, 40, 71, 24))
        self.mod2_type_combo.setObjectName(_fromUtf8("mod2_type_combo"))
        self.mod2_type_combo.addItem(_fromUtf8(""))
        self.mod2_type_combo.addItem(_fromUtf8(""))
        self.verticalLayoutWidget_9 = QtGui.QWidget(self.groupBox_9)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(150, 30, 171, 131))
        self.verticalLayoutWidget_9.setObjectName(_fromUtf8("verticalLayoutWidget_9"))
        self.mod2_plot_layout = QtGui.QVBoxLayout(self.verticalLayoutWidget_9)
        self.mod2_plot_layout.setMargin(0)
        self.mod2_plot_layout.setObjectName(_fromUtf8("mod2_plot_layout"))
        self.groupBox_10 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_10.setGeometry(QtCore.QRect(20, 590, 341, 171))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.detector_check = QtGui.QCheckBox(self.groupBox_10)
        self.detector_check.setGeometry(QtCore.QRect(10, 20, 79, 21))
        self.detector_check.setObjectName(_fromUtf8("detector_check"))
        self.label_41 = QtGui.QLabel(self.groupBox_10)
        self.label_41.setGeometry(QtCore.QRect(20, 70, 53, 21))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.label_42 = QtGui.QLabel(self.groupBox_10)
        self.label_42.setGeometry(QtCore.QRect(20, 91, 53, 20))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.label_43 = QtGui.QLabel(self.groupBox_10)
        self.label_43.setGeometry(QtCore.QRect(20, 110, 53, 21))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.detector_start_text = QtGui.QLineEdit(self.groupBox_10)
        self.detector_start_text.setGeometry(QtCore.QRect(70, 66, 61, 23))
        self.detector_start_text.setObjectName(_fromUtf8("detector_start_text"))
        self.detector_stop_text = QtGui.QLineEdit(self.groupBox_10)
        self.detector_stop_text.setGeometry(QtCore.QRect(70, 86, 61, 23))
        self.detector_stop_text.setObjectName(_fromUtf8("detector_stop_text"))
        self.detector_step_text = QtGui.QLineEdit(self.groupBox_10)
        self.detector_step_text.setGeometry(QtCore.QRect(70, 106, 61, 23))
        self.detector_step_text.setObjectName(_fromUtf8("detector_step_text"))
        self.label_44 = QtGui.QLabel(self.groupBox_10)
        self.label_44.setGeometry(QtCore.QRect(20, 45, 53, 20))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.detector_type_combo = QtGui.QComboBox(self.groupBox_10)
        self.detector_type_combo.setEnabled(False)
        self.detector_type_combo.setGeometry(QtCore.QRect(70, 40, 71, 24))
        self.detector_type_combo.setObjectName(_fromUtf8("detector_type_combo"))
        self.detector_type_combo.addItem(_fromUtf8(""))
        self.detector_type_combo.addItem(_fromUtf8(""))
        self.verticalLayoutWidget_10 = QtGui.QWidget(self.groupBox_10)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(150, 30, 171, 131))
        self.verticalLayoutWidget_10.setObjectName(_fromUtf8("verticalLayoutWidget_10"))
        self.detector_plot_layout = QtGui.QVBoxLayout(self.verticalLayoutWidget_10)
        self.detector_plot_layout.setMargin(0)
        self.detector_plot_layout.setObjectName(_fromUtf8("detector_plot_layout"))
        self.run_button = QtGui.QPushButton(self.centralwidget)
        self.run_button.setGeometry(QtCore.QRect(20, 763, 161, 41))
        self.run_button.setObjectName(_fromUtf8("run_button"))
        self.save_settings_button = QtGui.QPushButton(self.centralwidget)
        self.save_settings_button.setGeometry(QtCore.QRect(960, 780, 91, 24))
        self.save_settings_button.setObjectName(_fromUtf8("save_settings_button"))
        self.load_settings_button = QtGui.QPushButton(self.centralwidget)
        self.load_settings_button.setGeometry(QtCore.QRect(870, 780, 91, 24))
        self.load_settings_button.setObjectName(_fromUtf8("load_settings_button"))
        self.minor_progress = QtGui.QProgressBar(self.centralwidget)
        self.minor_progress.setGeometry(QtCore.QRect(370, 750, 291, 23))
        self.minor_progress.setProperty("value", 0)
        self.minor_progress.setObjectName(_fromUtf8("minor_progress"))
        self.major_progress = QtGui.QProgressBar(self.centralwidget)
        self.major_progress.setGeometry(QtCore.QRect(370, 780, 291, 23))
        self.major_progress.setProperty("value", 0)
        self.major_progress.setObjectName(_fromUtf8("major_progress"))
        self.label_45 = QtGui.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(570, 10, 91, 16))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.timestamp_label = QtGui.QLabel(self.centralwidget)
        self.timestamp_label.setGeometry(QtCore.QRect(670, 10, 131, 16))
        self.timestamp_label.setText(_fromUtf8(""))
        self.timestamp_label.setObjectName(_fromUtf8("timestamp_label"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1060, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.mod1_type_combo.setCurrentIndex(1)
        self.mod2_type_combo.setCurrentIndex(1)
        self.detector_type_combo.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.laser_sections_combo.setItemText(0, _translate("MainWindow", "DC Test Station", None))
        self.laser_sections_combo.setItemText(1, _translate("MainWindow", "RF Test Station (TOSA)", None))
        self.laser_sections_combo.setItemText(2, _translate("MainWindow", "RF Test Station (COC)", None))
        self.laser_sections_combo.setItemText(3, _translate("MainWindow", "SFP DACs", None))
        self.laser_sections_combo.setItemText(4, _translate("MainWindow", "Dummy", None))
        self.label.setText(_translate("MainWindow", "Laser Connection", None))
        self.label_2.setText(_translate("MainWindow", "UID", None))
        self.label_3.setText(_translate("MainWindow", "Stage", None))
        self.laser_stage_combo.setItemText(0, _translate("MainWindow", "BAR", None))
        self.laser_stage_combo.setItemText(1, _translate("MainWindow", "DIE", None))
        self.laser_stage_combo.setItemText(2, _translate("MainWindow", "COC", None))
        self.laser_stage_combo.setItemText(3, _translate("MainWindow", "FOC", None))
        self.laser_stage_combo.setItemText(4, _translate("MainWindow", "TOSA", None))
        self.laser_stage_combo.setItemText(5, _translate("MainWindow", "SFP", None))
        self.laser_stage_combo.setItemText(6, _translate("MainWindow", "DUMMY", None))
        self.label_4.setText(_translate("MainWindow", "Filepath Base", None))
        self.groupBox.setTitle(_translate("MainWindow", "Mirror 1", None))
        self.mirror1_check.setText(_translate("MainWindow", "Enabled", None))
        self.label_5.setText(_translate("MainWindow", "Start", None))
        self.label_6.setText(_translate("MainWindow", "Stop", None))
        self.label_7.setText(_translate("MainWindow", "Step", None))
        self.label_8.setText(_translate("MainWindow", "IV Type", None))
        self.mirror1_type_combo.setItemText(0, _translate("MainWindow", "Current", None))
        self.mirror1_type_combo.setItemText(1, _translate("MainWindow", "Voltage", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Mirror 2", None))
        self.mirror2_check.setText(_translate("MainWindow", "Enabled", None))
        self.label_9.setText(_translate("MainWindow", "Start", None))
        self.label_10.setText(_translate("MainWindow", "Stop", None))
        self.label_11.setText(_translate("MainWindow", "Step", None))
        self.label_12.setText(_translate("MainWindow", "IV Type", None))
        self.mirror2_type_combo.setItemText(0, _translate("MainWindow", "Current", None))
        self.mirror2_type_combo.setItemText(1, _translate("MainWindow", "Voltage", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Gain", None))
        self.gain_check.setText(_translate("MainWindow", "Enabled", None))
        self.label_13.setText(_translate("MainWindow", "Start", None))
        self.label_14.setText(_translate("MainWindow", "Stop", None))
        self.label_15.setText(_translate("MainWindow", "Step", None))
        self.label_16.setText(_translate("MainWindow", "IV Type", None))
        self.gain_type_combo.setItemText(0, _translate("MainWindow", "Current", None))
        self.gain_type_combo.setItemText(1, _translate("MainWindow", "Voltage", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "SOA 1", None))
        self.soa1_check.setText(_translate("MainWindow", "Enabled", None))
        self.label_17.setText(_translate("MainWindow", "Start", None))
        self.label_18.setText(_translate("MainWindow", "Stop", None))
        self.label_19.setText(_translate("MainWindow", "Step", None))
        self.label_20.setText(_translate("MainWindow", "IV Type", None))
        self.soa1_type_combo.setItemText(0, _translate("MainWindow", "Current", None))
        self.soa1_type_combo.setItemText(1, _translate("MainWindow", "Voltage", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "SOA 2", None))
        self.soa2_check.setText(_translate("MainWindow", "Enabled", None))
        self.label_21.setText(_translate("MainWindow", "Start", None))
        self.label_22.setText(_translate("MainWindow", "Stop", None))
        self.label_23.setText(_translate("MainWindow", "Step", None))
        self.label_24.setText(_translate("MainWindow", "IV Type", None))
        self.soa2_type_combo.setItemText(0, _translate("MainWindow", "Current", None))
        self.soa2_type_combo.setItemText(1, _translate("MainWindow", "Voltage", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Laser Phase", None))
        self.laspha_check.setText(_translate("MainWindow", "Enabled", None))
        self.label_25.setText(_translate("MainWindow", "Start", None))
        self.label_26.setText(_translate("MainWindow", "Stop", None))
        self.label_27.setText(_translate("MainWindow", "Step", None))
        self.label_28.setText(_translate("MainWindow", "IV Type", None))
        self.laspha_type_combo.setItemText(0, _translate("MainWindow", "Current", None))
        self.laspha_type_combo.setItemText(1, _translate("MainWindow", "Voltage", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Phase 1", None))
        self.phase1_check.setText(_translate("MainWindow", "Enabled", None))
        self.label_29.setText(_translate("MainWindow", "Start", None))
        self.label_30.setText(_translate("MainWindow", "Stop", None))
        self.label_31.setText(_translate("MainWindow", "Step", None))
        self.label_32.setText(_translate("MainWindow", "IV Type", None))
        self.phase1_type_combo.setItemText(0, _translate("MainWindow", "Current", None))
        self.phase1_type_combo.setItemText(1, _translate("MainWindow", "Voltage", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Modulator 1", None))
        self.mod1_check.setText(_translate("MainWindow", "Enabled", None))
        self.label_33.setText(_translate("MainWindow", "Start", None))
        self.label_34.setText(_translate("MainWindow", "Stop", None))
        self.label_35.setText(_translate("MainWindow", "Step", None))
        self.label_36.setText(_translate("MainWindow", "IV Type", None))
        self.mod1_type_combo.setItemText(0, _translate("MainWindow", "Current", None))
        self.mod1_type_combo.setItemText(1, _translate("MainWindow", "Voltage", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "Modulator 2", None))
        self.mod2_check.setText(_translate("MainWindow", "Enabled", None))
        self.label_37.setText(_translate("MainWindow", "Start", None))
        self.label_38.setText(_translate("MainWindow", "Stop", None))
        self.label_39.setText(_translate("MainWindow", "Step", None))
        self.label_40.setText(_translate("MainWindow", "IV Type", None))
        self.mod2_type_combo.setItemText(0, _translate("MainWindow", "Current", None))
        self.mod2_type_combo.setItemText(1, _translate("MainWindow", "Voltage", None))
        self.groupBox_10.setTitle(_translate("MainWindow", "On-Chip Detector", None))
        self.detector_check.setText(_translate("MainWindow", "Enabled", None))
        self.label_41.setText(_translate("MainWindow", "Start", None))
        self.label_42.setText(_translate("MainWindow", "Stop", None))
        self.label_43.setText(_translate("MainWindow", "Step", None))
        self.label_44.setText(_translate("MainWindow", "IV Type", None))
        self.detector_type_combo.setItemText(0, _translate("MainWindow", "Current", None))
        self.detector_type_combo.setItemText(1, _translate("MainWindow", "Voltage", None))
        self.run_button.setText(_translate("MainWindow", "RUN", None))
        self.save_settings_button.setText(_translate("MainWindow", "Save Settings", None))
        self.load_settings_button.setText(_translate("MainWindow", "Load Settings", None))
        self.label_45.setText(_translate("MainWindow", "Last timestamp:", None))

